name: Entando Docs
on: [push]
env:
  DOCS_DIR: vuepress
jobs:
  run-check-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: vuepress/yarn.lock
      - run: |
          cd $GITHUB_WORKSPACE/$DOCS_DIR
          yarn install
          yarn docs:check-md